name: dgml
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - brotlipy=0.7.0
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - conda=4.10.3
  - conda-package-handling=1.7.3
  - cryptography=3.4.7
  - idna=2.10
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.1.3
  - pycosat=0.6.3
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.9.6
  - readline=8.1
  - requests=2.25.1
  - ruamel_yaml=0.15.100
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - tqdm=4.61.2
  - tzdata=2021a
  - urllib3=1.26.6
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - pip:
      - -r requirements.txt
